### ISSUE TITLE
dynmap-residence not working with Residence 2.6.6

### ISSUE THREAD

**Issue by Heliwr** [webbukkit/dynmap-residence#5]
Since updating to Residence 2.6.6, residences are no longer showing on the dynmap page. There are no error messages in the console, but enabling the Residence layer on dynmap does nothing. I have tried both dynmap-residence 0.30 and 0.40 with the same results.

Running Residence 2.6.6, dynmap-residence 0.40, and dynmap 0.80.

**Comment by mikeprimm** [comment]
Residence 2.6.6 isn't release level at present - I'll give it a look, in any case, but any corrective action will be limited to what does not hurt support for the existing released versions.

**Comment by mikeprimm** [comment]
Found root of problem - its due to a change to the API for listing residence IDs in Residence.  I've requested to have it changed back - the API used to return the IDs of all the residences, while the current one is only returning hidden ones AND is only returning them presentation formatted (color codes, etc).  If they don't revert the change, I'll work on a workaround, if possible.

**Comment by Heliwr** [comment]
Thanks for looking into this, I'll keep an eye on their github commits for a fix.

edit: and it looks like the fix has been pushed, I'll test at the next scheduled server restart in a couple hours.
edit2: still not working with the latest snapshot.

**Comment by t00thpick1** [comment]
Should have fixed that with a commit just made(On Residence)

**Comment by Heliwr** [comment]
Sorry for the delayed response, I can confirm that the most recent development snapshot of Residence is now playing well with dynmap-residence versions 0.80 and 0.90.

**Comment by mikeprimm** [comment]
Thanks for the verify!
